### ISSUE TITLE
Pequeños comentarios

### ISSUE THREAD

**Issue by kallookoo** [aitormendez/menu-acordeon#1]
Hola Aitor,
Te comento algunos detalles:
* No aplicas los filtros predeterminados.
* No escapas las variables
* No añades los elementos extras de cada enlace si existiesen, como title, ref

Los puntos anteriores son importantes tanto por seguridad, accesibilidad, y para permitir su modificacion si fuese necesario.

Otros puntos no tan importantes, pero si necesarios para su implementacion al publicarlo:
* No existe el archivo js para el efecto acordeon
* No añades un ejemplo de codigo para implementarlo.

Un pensamiento personal:
Yo no lo consideraria un plugin de WordPress, porque realmente no añades funciones nuevas, mas bien es una caracteristica o añadido para un theme.

Igualmente enhorabuena, por tu trabajo, sigue asi.

**Comment by kallookoo** [comment]
Importante:
El codigo soporta versiones de PHP inferiores a 7.0, lo comento porque '[]' para definir un array no existe en esas versiones

**Comment by aitormendez** [comment]
@kallookoo No sé cómo agradecerte estos comentarios! Es justo lo que necesito para aprender. Pues ya que me has ofrecido estos consejos, te voy a preguntar por las cosas que no entiendo.

Lo primero, sobre la cuestión de los filtros. ¿Qué filtros exactamente? El tema de escapar variables puedo mirarlo en la documentación de WP pero, para esto de los filtros, necesito algo más de guía.

Estuve mirando la función `_wp_menu_item_classes_by_context` que me comentaste, para añadir las clases, pero pone en la documentación que no se debe usar por desarrolladores. Es para uso interno y tampoco me queda claro cómo se usa, en caso de hacerlo.

Respecto a la funcionalidad del acordeón, el objetivo para completar el plugin sería poder incluir todo el código. Ahora mismo está distribuido por distintos directorios del tema:

Primero, pasar al JS un array con los items de menú, tal como los ha configurado el usuario:

https://bitbucket.org/aitormendez/esterpartegas/src/9f5fb77e9417403ad173530e83a660b84f930332/web/app/themes/ep/app/setup.php#lines-134:154

Segundo, el JS propiamente, que está hecho con jQuery. Hace el efecto acordeón y también que la posición del acordeón sea persistente (que se quede abierta la pestaña elegida cuando vas a otra página), con `sessionStorage`:

https://bitbucket.org/aitormendez/esterpartegas/src/9f5fb77e9417403ad173530e83a660b84f930332/web/app/themes/ep/resources/assets/scripts/routes/common.js#lines-8:48

Por último, el CSS correspondiente.

https://bitbucket.org/aitormendez/esterpartegas/src/master/web/app/themes/ep/resources/assets/styles/layouts/_header.scss

La verdad, me gustaría mucho poder juntarlo todo en el plugin, pero aún no sé hacerlo. Tengo que aprender. De momento sólo he hecho plugins de un solo archivo.

Y, por último, ¿Cómo se hace para limitar la versión de PHP del plugin?

En fin, son muchas cosas. Contesta lo que te apetezca, sin compromiso. Te gradezco mucho tus comentarios.

**Comment by kallookoo** [comment]
Hola, te voy respondiendo...

 > Lo primero, sobre la cuestión de los filtros. ¿Qué filtros exactamente? 

Casi todo en WordPress, Plugins y Themes estan diseñados para permitir al desarrollador modificar el resultado de una function por ejemplo. Y en la class Walker_Nav_Menu hay unos cuantos.
Puedes mirar start_el en este https://github.com/WordPress/WordPress/blob/master/wp-includes/class-walker-nav-menu.php#L118
No me extiendo mucho en el tema de los filtros pero en tu caso y si lo quieres publicar es recomendable ya que puede ser que un theme añada una clase, etc... o el mismo WordPress

 > El tema de escapar variables puedo mirarlo en la documentación de WP ...

Esto es sencillo por seguridad, es recomendado (obligatorio) escapar las variables, ejemplo:
Imagina que recibes una variable con una url, si por algun motivo esa url tiene codigo ejecutable y no se escapa con `esc_url` o `esc_url_raw` la variable, cuando imprimas esa url y el usuario visite esa pagina ejecutaria el codigo.
Depende del contexto se usan diferentes funciones y  te toca buscarla en el codex o developer normalmente empiezan por `esc_` o `sanitize_`

> Estuve mirando la función `_wp_menu_item_classes_by_context` que me comentaste ...

Por norma las funciones marcadas como privada no se usan, concretamente para tu codigo como esta ahora esa function no se puede usar y deberias añadirlas manualmente.

 > Sobre como incluir css, js lo mejor es que mires:

https://codex.wordpress.org/Main_Page (Write a Plugin seccion)
https://developer.wordpress.org/plugins/
Dependiendo de donde es necesario usar un action u otro.

 > Y, por último, ¿Cómo se hace para limitar la versión de PHP del plugin?

Como tu plugin es nuevo y el WordPress ya pide la version 7 de PHP no seria necesario y solo es necesario añadir al readme.txt el texto "Require PHP: 7.0"
Aqui hay un dilema o no, que es que compatibilidad quieres dar, por ejemplo yo hice una pequeña encuesta en twitter que lo puedes ver aqui: https://twitter.com/kallookoo/status/1035538006759952386 ( mira los comentarios tambien )
Yo de momento y por falta de tiempo/ganas mis plugins soportan la 5.4 en adelante, aunque tengo intencion de solo dar soporte a 7.0 en adelante.
Si te quieres asegurar puedes usar version_compare para determinar la version y mostrar por ejemplo un admin_notices.

> Comentarios

Una cosa que tienes que hacer es separar el codigo del BackEnd y FrontEnd para no cargar o registrar nada que no sea necesario.
Te pondria algun link pero en los enlaces que puse mas arriba veras ejemplos, etc...

Saludos

**Comment by aitormendez** [comment]
Gracias, Sergio. Tengo para un rato de estudiar. ;)

**Comment by aitormendez** [comment]
https://github.com/aitormendez/menu-acordeon/commit/d83928cd4e9795b29abd07bcc8a76fdd9b087635

**Comment by kallookoo** [comment]
Bueno, aqui te dejo una base: https://github.com/kallookoo/menu-acordeon/ ahora ya tienes por donde empezar...

**Comment by aitormendez** [comment]
Buenísimo. Un vistazo rápido ya me ha aclarado muchas cosas. Ahora, además de verlo despacio, tengo que leer le handbook, tal como sugieres en un comentario. Me llevará un tiempo pero me va a permitir dar un paso de gigante.

El tema de namespace, lo tenía pendiente de implementar.

El enrutado de JS se hace con un [sistema de routing en roots](https://github.com/roots/sage/blob/master/resources/assets/scripts/util/Router.js), pero en el plugin, no sé. Supongo que con condicionales en el `enqueue_script` ¿no?

**Comment by kallookoo** [comment]
El tema de styles y scripts:
Basicamente lo controla https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/class.wp-scripts.php 
Si te fijas en este archivo donde se declaran las functions lo veras, https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/functions.wp-scripts.php

Un buen recurso es https://developer.wordpress.org te servira mucho para saber si una function tiene un filtro, para que sirve x filtro, etc... en el WordPress hay functions definidas para hacerlo mas entendible cuando lees el nombre, un caso por ejemplo es `get_user_meta` que si miras el codigo llama a `get_metadata` y asi unas cuantas, y en este caso no hay ningun filtro en `get_user_meta` pero si que tienes en `get_metadata`, asi que es recomendable mirar el codigo para ver como funciona y comprobrar si tiene filtros, actions, globals, etc...

Y ya para acabar que no te comente es el uso de `wp_cache_set` y `wp_cache_get` para no realizar multiple llamadas a la DB o cierto contenido. No lo confundas con los plugins de cache.
Aqui puedes verlo:
https://codex.wordpress.org/Class_Reference/WP_Object_Cache
https://developer.wordpress.org/reference/classes/wp_object_cache/
https://core.trac.wordpress.org/browser/tags/4.9/src/wp-includes/cache.php

**Comment by aitormendez** [comment]
Una pregunta rápida. He estado leyendo sobre nonces y veo que es necesario en otros plugins pero no en este. Es decir, no veo nada que haya que validar porque no se interacciona con la BD, más allá de recuperar contenidos y mostrarlos. ¿correcto?

**Comment by kallookoo** [comment]
Buenas Aitor,
No me molesta responderte, pero ese tipo de preguntas ya tienes la respuesta en el codex o developer y es mejor para ti leerlo aunque eso signifique que lo mires 1000 veces al dia.
Entiendo que como estas empezando tengas muchas dudas, pero no creo que sea buena idea que te acostumbres ha preguntarme cosas que con una busqueda lo encuentras.
Dicho eso los nonces se usan para diferentes cosas como pueden ser; ajax, cuando el plugin necesita guardar/borrar/editar su contenido o modificar el core cuando guarda/borra/edita posts, pages, taxonomies, options.
Link para consultar: https://developer.wordpress.org/plugins/security/nonces/

Repito que no me molesta y puedes preguntar en el foro cuando quieras y si lo veo te respondo.
Saludos!!!

**Comment by aitormendez** [comment]
Precísamente te pregunto porque me he leído el codex y presenta una aparente incongruencia entre una de tus indicaciones (utilizar y validar nounces. Calificada, además, como obligatoria) y la funcionalidad de el plugin. La incongruencia es que el plugin no guarda ni edita nada, por lo que la gestión de nounces no parece necesaria y, por el contrario, tú me indicas que es obligatorio su uso.

Te pregunto, entonces, si estoy en lo cierto (que no debo usar nounces en este plugin) para saber, en caso afirmativo, que tus recomendaciones son de carácter general, y no específicas de este plugin. Esto es imposible de ver en el codex aunque lo lea mil veces, porque es una duda referida a tus explicaciones.

Te agradezco mucho todo el esfuerzo que estás haciendo. Entiendo que es mucho y te lo agradezco enormemente. A la vez, te aseguro que yo estoy haciendo otro tanto. Leo toneladas de documentación antes de preguntar. Un abrazo fuerte!

**Comment by kallookoo** [comment]
Respuesta rapida: 
En tu plugin no es necesario.

Respuesta mas extensa:

Yo te hice una base generica y comentarios genericos.
Aunque te añadi el Walker ya que es lo que usarias en tu caso, lo hice para que vieses una manera de hacerlo de entre otras.
Creo que te estas tomando al pie de la letra todo lo que escribi en ese ejemplo de plugin y no deberias, cada plugin necesita ciertas cosas. Por ejemplo si solo añades  un filtro para x motivo no seria necesario hacer una clase, etc... haces una function y punto. Aqui cada programador ya decide lo que considera mejor, No se! hay plugins que todo lo hacen usando functions otros que mezclan y otros que todo es classes, traits, interfaces. 
Luego tambien tienes el tema del Pattern Singleton o Static class, etc...

Lo importante aqui independientemente como lo hagas es que tomes las mayores precauciones para mantener la seguidad del WordPress.

Aqui puedes ver diferentes boilerplate y veras mas ejemplos:
https://github.com/search?l=PHP&q=wordpress+plugin+boilerplate&type=Repositories

Ni los he probado y revisado, es otro recurso que puedes ver.

**Comment by aitormendez** [comment]
Ok, duda aclarada! También estuve leyendo ayer sobre singleton y static clases. Tengo que abordar poco a poco toda la info que me has dado. Mil gracias de nuevo.
